datasets:
  age_gender_race_data: dataset/UTKface_inthewild/part1
  fer_train: dataset/FER/train
  fer_validation: dataset/FER/validation
  predictor_path: models/shape_predictor_68_face_landmarks.dat
logging:
  file: project.log
  level: DEBUG
model_params:
  dense_units_1: 256
  dense_units_2: 128
  dense_units_3: 64
  dense_units_4: 32
  dense_units_5: 16
  dropout_rate: 0.5
  input_shape:
  - 256
  - 256
  - 3
  leaky_relu_slope: 0.01
  n_classes: 7
  num_races: 5
  regularization_rate: 0.001
  batch_size: 32  # Add this line to specify the batch size
race_label_map:
  0: White
  1: Black
  2: Asian
  3: Indian
  4: Others
server:
  host: 0.0.0.0
  port: 5000
validation_split: 0.2
version: '12.3'
