datasets:
  fer_train: dataset/FER/train
  fer_validation: dataset/FER/validation
  age_gender_race_data: dataset/UTKface_inthewild/part1  # Path to your age, gender, and race dataset directory
  predictor_path: models/shape_predictor_68_face_landmarks.dat
validation_split: 0.2  # Validation split for your dataset
logging:
  file: project.log
  level: DEBUG
model_params:
  dense_units_1: 256
  dense_units_2: 128
  dense_units_3: 64
  dense_units_4: 32
  dense_units_5: 16
  dropout_rate: 0.5
  input_shape: [256, 256, 3]  # Input shape for images
  leaky_relu_slope: 0.01
  n_classes: 7
  regularization_rate: 0.001
  num_races: 5  # Number of race classes
server:
  host: 0.0.0.0
  port: 5002
version: '12.3'
race_label_map:
  0: "White"
  1: "Black"
  2: "Asian"
  3: "Indian"
  4: "Others"
